name = "qianmo"
type = "static"
account_id = "3b322f9a2ef5a9bf42265e6297e89839"  # 从Cloudflare控制台获取
workers_dev = false
route = ""
zone_id = ""  # 可选，绑定自定义域名时需要

[build]
command = ""  # 无构建步骤留空，若用Jekyll则填"jekyll build"
publish = "."  # 静态文件目录（如Jekyll构建后是"_site"）
